#define DS reg[0]
#define IP reg[5]
#define CC reg[8]
#define AC reg[9]
#define AX reg[10]
#define BX reg[11]
#define CX reg[12]
#define DX reg[13]
#define EX reg[14]
#define FX reg[15]
#define d Flags[0]
#define b Flags[1]
#define c Flags[2]

